export const FIREBASE = {
  APIKEY: process.env.NEXT_PUBLIC_FIREBASE_APIKEY,
  AUTHDOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN,
  PROJECTID: process.env.NEXT_PUBLIC_FIREBASE_PROJECTID,
  STORAGEBUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET,
  MESSAGINGSENDERID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID,
  APPID: process.env.NEXT_PUBLIC_FIREBASE_APPID,
  MEASUREMENTID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENTID,
};
